import { useState, useEffect } from 'react';
import { useAuth } from '../lib/auth-context';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { Plus, Building2, MapPin, Edit, Trash, ImageIcon } from 'lucide-react';
import { toast } from 'sonner';
import { projectId, publicAnonKey } from '../../../utils/supabase/info';

interface Customer {
  row_id: string;
  customer: string;
  customer_logo: string | null;
}

interface District {
  row_id: string;
  customer_district_id: string;
  customer_district: string;
  customer_address: string | null;
  district_contact: string | null;
  customer_email: string | null;
  customer_phone_number: string | null;
  customer: string;
  customer_name: string | null;
  customer_logo: string | null;
}

export default function CustomersNew() {
  const { accessToken } = useAuth();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [districts, setDistricts] = useState<District[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCustomerDialog, setShowCustomerDialog] = useState(false);
  const [showDistrictDialog, setShowDistrictDialog] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [editingDistrict, setEditingDistrict] = useState<District | null>(null);
  const [selectedTab, setSelectedTab] = useState<'customers' | 'districts'>('customers');
  const [selectedCustomer, setSelectedCustomer] = useState<string>('');
  const [districtName, setDistrictName] = useState<string>('');
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');

  const baseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-64775d98`;

  useEffect(() => {
    if (accessToken) {
      loadData();
    } else {
      setLoading(false);
    }
  }, [accessToken]);

  const loadData = async () => {
    if (!accessToken) return;
    
    setLoading(true);
    try {
      const [customersRes, districtsRes] = await Promise.all([
        fetch(`${baseUrl}/customers`, {
          headers: { 'Authorization': `Bearer ${accessToken ?? publicAnonKey}` }
        }),
        fetch(`${baseUrl}/districts`, {
          headers: { 'Authorization': `Bearer ${accessToken ?? publicAnonKey}` }
        })
      ]);

      const customersData = await customersRes.json();
      const districtsData = await districtsRes.json();

      // Guard against non-array error responses so the table never crashes.
      setCustomers(Array.isArray(customersData) ? customersData : []);
      setDistricts(Array.isArray(districtsData) ? districtsData : []);
      
      console.log('Loaded customers:', customersData);
      console.log('Loaded districts:', districtsData);
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  const handleCreateCustomer = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    
    try {
      const response = await fetch(`${baseUrl}/customers`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken ?? publicAnonKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          customer: formData.get('customer'),
          customer_logo: formData.get('customer_logo') || null
        })
      });

      if (response.ok) {
        toast.success('Customer created successfully!');
        setShowCustomerDialog(false);
        loadData();
        e.currentTarget.reset();
      } else {
        const error = await response.json();
        toast.error('Failed to create customer: ' + error.error);
      }
    } catch (error) {
      console.error('Error creating customer:', error);
      toast.error('Failed to create customer');
    }
  };

  const handleUpdateCustomer = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!editingCustomer) return;
    
    const formData = new FormData(e.currentTarget);
    
    try {
      const response = await fetch(`${baseUrl}/customers/${editingCustomer.row_id}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${accessToken ?? publicAnonKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          customer: formData.get('customer'),
          customer_logo: formData.get('customer_logo')
        })
      });

      if (response.ok) {
        toast.success('Customer updated successfully!');
        setShowCustomerDialog(false);
        setEditingCustomer(null);
        loadData();
      } else {
        const error = await response.json();
        toast.error('Failed to update customer: ' + error.error);
      }
    } catch (error) {
      console.error('Error updating customer:', error);
      toast.error('Failed to update customer');
    }
  };

  const handleDeleteCustomer = async (id: string) => {
    if (!confirm('Are you sure you want to delete this customer?')) return;
    
    try {
      const response = await fetch(`${baseUrl}/customers/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${accessToken ?? publicAnonKey}` }
      });

      if (response.ok) {
        toast.success('Customer deleted successfully!');
        loadData();
      } else {
        toast.error('Failed to delete customer');
      }
    } catch (error) {
      console.error('Error deleting customer:', error);
      toast.error('Failed to delete customer');
    }
  };

  const handleCreateDistrict = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    
    // Validate that we have the required values from state
    if (!selectedCustomer) {
      toast.error('Please select a customer');
      return;
    }
    
    if (!districtName || !districtName.trim()) {
      toast.error('Please enter a district name');
      return;
    }
    
    if (!autoGeneratedId || !autoGeneratedId.trim()) {
      toast.error('District ID is required. Please select a customer and enter a district name.');
      return;
    }
    
    // Use state values for controlled inputs, FormData for others
    const districtData = {
      customer_district_id: autoGeneratedId.trim(), // Use state value
      customer_district: districtName.trim(), // Use state value
      customer_address: formData.get('customer_address'),
      district_contact: formData.get('district_contact') || null,
      customer_email: formData.get('customer_email') || null,
      customer_phone_number: formData.get('customer_phone_number') || null,
      customer: selectedCustomer // Use state value
    };

    console.log('Creating district with data:', districtData);
    
    try {
      const response = await fetch(`${baseUrl}/districts`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken ?? publicAnonKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(districtData)
      });

      if (response.ok) {
        toast.success('District created successfully!');
        setShowDistrictDialog(false);
        setSelectedCustomer('');
        setDistrictName('');
        setAutoGeneratedId('');
        loadData();
      } else {
        const error = await response.json();
        console.error('Failed to create district:', error);
        toast.error('Failed to create district: ' + error.error);
      }
    } catch (error) {
      console.error('Error creating district:', error);
      toast.error('Failed to create district');
    }
  };

  const handleUpdateDistrict = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!editingDistrict) return;
    
    const formData = new FormData(e.currentTarget);
    
    try {
      const response = await fetch(`${baseUrl}/districts/${editingDistrict.row_id}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${accessToken ?? publicAnonKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          customer_district_id: formData.get('customer_district_id'),
          customer_district: formData.get('customer_district'),
          customer_address: formData.get('customer_address'),
          district_contact: formData.get('district_contact'),
          customer_email: formData.get('customer_email'),
          customer_phone_number: formData.get('customer_phone_number'),
          customer: formData.get('customer')
        })
      });

      if (response.ok) {
        toast.success('District updated successfully!');
        setShowDistrictDialog(false);
        setEditingDistrict(null);
        loadData();
      } else {
        const error = await response.json();
        toast.error('Failed to update district: ' + error.error);
      }
    } catch (error) {
      console.error('Error updating district:', error);
      toast.error('Failed to update district');
    }
  };

  const handleDeleteDistrict = async (id: string) => {
    if (!confirm('Are you sure you want to delete this district?')) return;
    
    try {
      const response = await fetch(`${baseUrl}/districts/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${accessToken ?? publicAnonKey}` }
      });

      if (response.ok) {
        toast.success('District deleted successfully!');
        loadData();
      } else {
        toast.error('Failed to delete district');
      }
    } catch (error) {
      console.error('Error deleting district:', error);
      toast.error('Failed to delete district');
    }
  };

  const openDistrictDialog = () => {
    setShowDistrictDialog(true);
    setSelectedCustomer('');
    setDistrictName('');
    setAutoGeneratedId('');
  };

  const closeDistrictDialog = () => {
    setShowDistrictDialog(false);
    setEditingDistrict(null);
    setSelectedCustomer('');
    setDistrictName('');
    setAutoGeneratedId('');
  };

  const openEditDistrict = (district: District) => {
    setEditingDistrict(district);
    setSelectedCustomer(district.customer);
    setDistrictName(district.customer_district);
    setAutoGeneratedId(''); // Don't auto-generate when editing
    setShowDistrictDialog(true);
  };

  const openEditCustomer = (customer: any) => {
    setEditingCustomer(customer);
    setShowCustomerDialog(true);
  };

  // Auto-generate district ID when customer or district name changes
  const handleCustomerChange = (customerId: string) => {
    setSelectedCustomer(customerId);
    generateDistrictId(customerId, districtName);
  };

  const handleDistrictNameChange = (name: string) => {
    setDistrictName(name);
    generateDistrictId(selectedCustomer, name);
  };

  const generateDistrictId = (customerId: string, districtNameVal: string) => {
    if (!customerId || !districtNameVal) {
      setAutoGeneratedId('');
      return;
    }

    const customer = customers.find(c => c.row_id === customerId);
    if (!customer) {
      setAutoGeneratedId('');
      return;
    }

    // Generate ID in format: CUSTOMER_DISTRICT (e.g., TWG_FAR)
    // Extract first 3 letters from customer name (skip non-letters)
    const customerLetters = customer.customer.toUpperCase().replace(/[^A-Z]/g, '');
    const customerPrefix = customerLetters.substring(0, 3) || 'CUS';
    
    // Extract first 3 letters from district name (skip non-letters)
    const districtLetters = districtNameVal.toUpperCase().replace(/[^A-Z]/g, '');
    const districtSuffix = districtLetters.substring(0, 3) || 'DIS';
    
    const generatedId = `${customerPrefix}_${districtSuffix}`;
    
    console.log('Auto-generating district ID:', {
      customerName: customer.customer,
      customerLetters,
      customerPrefix,
      districtName: districtNameVal,
      districtLetters,
      districtSuffix,
      generatedId
    });
    
    setAutoGeneratedId(generatedId);
  };

  if (loading) {
    return <div className="p-8">Loading...</div>;
  }

  return (
    <div className="p-8">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Customer & District Management</h1>
          <p className="text-gray-600 mt-2">
            Manage your wireline company customers and their districts
          </p>
        </div>

        <Tabs defaultValue="customers" className="space-y-6">
          <TabsList>
            <TabsTrigger value="customers">
              <Building2 className="w-4 h-4 mr-2" />
              Customers
            </TabsTrigger>
            <TabsTrigger value="districts">
              <MapPin className="w-4 h-4 mr-2" />
              Districts
            </TabsTrigger>
          </TabsList>

          {/* Customers Tab */}
          <TabsContent value="customers">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Customers ({customers.length})</CardTitle>
                  <Button onClick={() => { setEditingCustomer(null); setShowCustomerDialog(true); }}>
                    <Plus className="w-4 h-4 mr-2" />
                    Add Customer
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Logo</TableHead>
                      <TableHead>Customer Name</TableHead>
                      <TableHead>Logo Path</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {customers.map((customer) => (
                      <TableRow key={customer.row_id}>
                        <TableCell>
                          {customer.customer_logo ? (
                            <img 
                              src={customer.customer_logo} 
                              alt={customer.customer}
                              className="h-10 w-auto object-contain"
                              onError={(e) => {
                                e.currentTarget.style.display = 'none';
                                e.currentTarget.nextElementSibling?.classList.remove('hidden');
                              }}
                            />
                          ) : null}
                          <div className={customer.customer_logo ? 'hidden' : 'flex items-center justify-center w-10 h-10 bg-gray-100 rounded'}>
                            <ImageIcon className="w-5 h-5 text-gray-400" />
                          </div>
                        </TableCell>
                        <TableCell className="font-medium">{customer.customer}</TableCell>
                        <TableCell className="text-sm text-gray-600">{customer.customer_logo || 'No logo'}</TableCell>
                        <TableCell>
                          <div className="flex gap-2">
                            <Button size="sm" variant="outline" onClick={() => openEditCustomer(customer)}>
                              <Edit className="w-4 h-4" />
                            </Button>
                            <Button size="sm" variant="destructive" onClick={() => handleDeleteCustomer(customer.row_id)}>
                              <Trash className="w-4 h-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                    {customers.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center text-gray-500 py-8">
                          No customers found. Create your first customer to get started.
                        </TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Districts Tab */}
          <TabsContent value="districts">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Districts ({districts.length})</CardTitle>
                  <Button onClick={openDistrictDialog}>
                    <Plus className="w-4 h-4 mr-2" />
                    Add District
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Customer</TableHead>
                      <TableHead>District ID</TableHead>
                      <TableHead>District Name</TableHead>
                      <TableHead>Address</TableHead>
                      <TableHead>Contact</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {districts.map((district) => (
                      <TableRow key={district.row_id}>
                        <TableCell>
                          <div className="flex items-center gap-3">
                            {district.customer_logo ? (
                              <img 
                                src={district.customer_logo} 
                                alt={district.customer_name}
                                className="h-8 w-auto object-contain"
                                onError={(e) => {
                                  e.currentTarget.style.display = 'none';
                                }}
                              />
                            ) : (
                              <div className="flex items-center justify-center w-8 h-8 bg-gray-100 rounded">
                                <Building2 className="w-4 h-4 text-gray-400" />
                              </div>
                            )}
                            <span className="font-medium">{district.customer_name || 'Unknown'}</span>
                          </div>
                        </TableCell>
                        <TableCell>{district.customer_district_id}</TableCell>
                        <TableCell>{district.customer_district}</TableCell>
                        <TableCell className="text-sm text-gray-600">{district.customer_address}</TableCell>
                        <TableCell className="text-sm text-gray-600">{district.district_contact || '-'}</TableCell>
                        <TableCell>
                          <div className="flex gap-2">
                            <Button size="sm" variant="outline" onClick={() => openEditDistrict(district)}>
                              <Edit className="w-4 h-4" />
                            </Button>
                            <Button size="sm" variant="destructive" onClick={() => handleDeleteDistrict(district.row_id)}>
                              <Trash className="w-4 h-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                    {districts.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={6} className="text-center text-gray-500 py-8">
                          No districts found. Create your first district to get started.
                        </TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Customer Dialog */}
        <Dialog open={showCustomerDialog} onOpenChange={closeCustomerDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>{editingCustomer ? 'Edit Customer' : 'Add New Customer'}</DialogTitle>
            </DialogHeader>
            <form onSubmit={editingCustomer ? handleUpdateCustomer : handleCreateCustomer} className="space-y-4">
              <div>
                <Label htmlFor="customer">Customer Name *</Label>
                <Input
                  id="customer"
                  name="customer"
                  defaultValue={editingCustomer?.customer || ''}
                  required
                />
              </div>
              <div>
                <Label htmlFor="customer_logo">Customer Logo Path</Label>
                <Input
                  id="customer_logo"
                  name="customer_logo"
                  defaultValue={editingCustomer?.customer_logo || ''}
                  placeholder="e.g., Customer Districts_Images/logo.png"
                />
              </div>
              <div className="flex gap-2 justify-end">
                <Button type="button" variant="outline" onClick={closeCustomerDialog}>
                  Cancel
                </Button>
                <Button type="submit">
                  {editingCustomer ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>

        {/* District Dialog */}
        <Dialog open={showDistrictDialog} onOpenChange={closeDistrictDialog}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>{editingDistrict ? 'Edit District' : 'Add New District'}</DialogTitle>
            </DialogHeader>
            <form onSubmit={editingDistrict ? handleUpdateDistrict : handleCreateDistrict} className="space-y-4">
              <div>
                <Label htmlFor="customer">Customer *</Label>
                <select
                  id="customer"
                  name="customer"
                  value={editingDistrict ? editingDistrict.customer : selectedCustomer}
                  required
                  className="w-full border border-gray-300 rounded-md p-2"
                  onChange={(e) => handleCustomerChange(e.target.value)}
                >
                  <option value="">Select a customer...</option>
                  {customers.map((customer) => (
                    <option key={customer.row_id} value={customer.row_id}>
                      {customer.customer}
                    </option>
                  ))}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="customer_district_id">District ID *</Label>
                  <Input
                    id="customer_district_id"
                    name="customer_district_id"
                    placeholder="e.g., BWL_FAR"
                    required
                    value={editingDistrict ? editingDistrict.customer_district_id : autoGeneratedId}
                    onChange={(e) => setAutoGeneratedId(e.target.value)}
                    className={autoGeneratedId && !editingDistrict ? 'bg-gray-50' : ''}
                  />
                  {autoGeneratedId && !editingDistrict && (
                    <p className="text-xs text-gray-500 mt-1">Auto-generated (editable)</p>
                  )}
                </div>
                <div>
                  <Label htmlFor="customer_district">District Name *</Label>
                  <Input
                    id="customer_district"
                    name="customer_district"
                    placeholder="e.g., BWL-Farmington"
                    required
                    value={districtName}
                    onChange={(e) => handleDistrictNameChange(e.target.value)}
                  />
                </div>
              </div>
              <div>
                <Label htmlFor="customer_address">Address</Label>
                <Input
                  id="customer_address"
                  name="customer_address"
                  defaultValue={editingDistrict?.customer_address || ''}
                  placeholder="Full address"
                />
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <Label htmlFor="district_contact">Contact Name</Label>
                  <Input
                    id="district_contact"
                    name="district_contact"
                    defaultValue={editingDistrict?.district_contact || ''}
                  />
                </div>
                <div>
                  <Label htmlFor="customer_email">Email</Label>
                  <Input
                    id="customer_email"
                    name="customer_email"
                    type="email"
                    defaultValue={editingDistrict?.customer_email || ''}
                  />
                </div>
                <div>
                  <Label htmlFor="customer_phone_number">Phone</Label>
                  <Input
                    id="customer_phone_number"
                    name="customer_phone_number"
                    defaultValue={editingDistrict?.customer_phone_number || ''}
                  />
                </div>
              </div>
              <div className="flex gap-2 justify-end">
                <Button type="button" variant="outline" onClick={closeDistrictDialog}>
                  Cancel
                </Button>
                <Button type="submit">
                  {editingDistrict ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}