-- ============================================================
-- FST APP MIGRATION — panel_change_log identity fix
-- Adds a GENERATED-BY-DEFAULT identity to fst_app.panel_change_log.id
--
-- Background: fst_app.panel_change_log.id was bigint NOT NULL with no
-- identity/sequence/default. The edge function's PUT /panels/:id
-- write-logging block inserts diff rows without supplying id, causing a
-- NOT NULL violation that was silently swallowed (panel saved, no history
-- row written). Adding the identity lets Postgres auto-assign id.
--
-- Applied to BOTH environments on 2026-07-01:
--   Production (gbllxumuogsncoiaksum) and Testing (qbexqpvzmssmifimlfos).
-- START WITH 2000 chosen because the max existing id at apply time was 1763.
-- Idempotent: only adds the identity if the column is not already an identity.
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'fst_app'
      AND table_name = 'panel_change_log'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE fst_app.panel_change_log
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2000);
  END IF;
END
$$;
